# -*- coding: utf-8 -*-
"""apex planet 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ab6untoagSSxoBdlxQI0FFsSLmeN6EXD
"""

# =====================================================
# TASK 4 - DATA STORYTELLING & STATISTICAL VALIDATION
# BANK CUSTOMER CHURN ANALYSIS
# =====================================================

# -----------------------------------------------------
# STEP 1 - IMPORT LIBRARIES
# -----------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# -----------------------------------------------------
# STEP 2 - UPLOAD CSV FILE
# -----------------------------------------------------

from google.colab import files

uploaded = files.upload()

# -----------------------------------------------------
# STEP 3 - LOAD DATASET
# -----------------------------------------------------

# Replace filename if needed. The uploaded file was 'Cleaned_Bank_Churn.csv'
df = pd.read_csv('Cleaned_Bank_Churn.csv')

# Convert 'Exited' column to numerical for easier analysis
df['Exited'] = df['Exited'].map({'Left': 1, 'Stayed': 0})

# -----------------------------------------------------
# STEP 4 - DISPLAY DATA
# -----------------------------------------------------

print("FIRST 5 ROWS")
display(df.head())

print("\nDATASET SHAPE")
print(df.shape)

print("\nDATASET INFO")
print(df.info())

print("\nSTATISTICAL SUMMARY")
display(df.describe())

# =====================================================
# STEP 5 - DATA STORYTELLING VISUALIZATIONS
# =====================================================

# -----------------------------------------------------
# STORY 1 - CUSTOMER CHURN DISTRIBUTION
# -----------------------------------------------------

plt.figure(figsize=(6,5))

sns.countplot(
    x='Exited',
    data=df
)

plt.title("Customer Churn Distribution")
plt.xlabel("Exited")
plt.ylabel("Count")

plt.show()

# -----------------------------------------------------
# STORY 2 - GENDER VS CHURN
# -----------------------------------------------------

plt.figure(figsize=(7,5))

sns.countplot(
    x='Gender',
    hue='Exited',
    data=df
)

plt.title("Gender vs Customer Churn")

plt.show()

# -----------------------------------------------------
# STORY 3 - AGE VS CHURN
# -----------------------------------------------------

plt.figure(figsize=(8,5))

sns.boxplot(
    x='Exited',
    y='Age',
    data=df
)

plt.title("Age Distribution by Churn")

plt.show()

# -----------------------------------------------------
# STORY 4 - BALANCE VS CHURN
# -----------------------------------------------------

plt.figure(figsize=(8,5))

sns.boxplot(
    x='Exited',
    y='Balance',
    data=df
)

plt.title("Balance Distribution by Churn")

plt.show()

# -----------------------------------------------------
# STORY 5 - CREDIT SCORE DISTRIBUTION
# -----------------------------------------------------

plt.figure(figsize=(8,5))

sns.histplot(
    df['CreditScore'],
    bins=30,
    kde=True
)

plt.title("Credit Score Distribution")

plt.show()

# -----------------------------------------------------
# STORY 6 - CORRELATION HEATMAP
# -----------------------------------------------------

plt.figure(figsize=(12,8))

numeric_df = df.select_dtypes(include=np.number)

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title("Correlation Heatmap")

plt.show()

# =====================================================
# STEP 6 - STATISTICAL VALIDATION
# =====================================================

print("\n===================================")
print("STATISTICAL VALIDATION")
print("===================================\n")

# -----------------------------------------------------
# TEST 1 - T-TEST
# AGE VS CHURN
# -----------------------------------------------------

churned_age = df[df['Exited'] == 1]['Age']
not_churned_age = df[df['Exited'] == 0]['Age']

t_stat, p_value = stats.ttest_ind(
    churned_age,
    not_churned_age
)

print("T-TEST : AGE VS CHURN")
print("T-Statistic :", t_stat)
print("P-Value     :", p_value)

if p_value < 0.05:
    print("RESULT : Significant difference in age.\n")
else:
    print("RESULT : No significant difference.\n")

# -----------------------------------------------------
# TEST 2 - CHI-SQUARE TEST
# GENDER VS CHURN
# -----------------------------------------------------

contingency_table = pd.crosstab(
    df['Gender'],
    df['Exited']
)

chi2, p, dof, expected = stats.chi2_contingency(
    contingency_table
)

print("CHI-SQUARE TEST : GENDER VS CHURN")
print("Chi2 Statistic :", chi2)
print("P-Value        :", p)

if p < 0.05:
    print("RESULT : Gender and churn are associated.\n")
else:
    print("RESULT : No significant association.\n")

# -----------------------------------------------------
# TEST 3 - CORRELATION TEST
# BALANCE VS ESTIMATED SALARY
# -----------------------------------------------------

correlation = df['Balance'].corr(
    df['EstimatedSalary']
)

print("CORRELATION TEST : BALANCE VS SALARY")
print("Correlation Value :", correlation)

if abs(correlation) > 0.5:
    print("RESULT : Strong correlation.\n")
elif abs(correlation) > 0.3:
    print("RESULT : Moderate correlation.\n")
else:
    print("RESULT : Weak correlation.\n")

# =====================================================
# STEP 7 - BUSINESS INSIGHTS
# =====================================================

print("\n===================================")
print("BUSINESS INSIGHTS")
print("===================================\n")

# Average age by churn
avg_age = df.groupby('Exited')['Age'].mean()

print("AVERAGE AGE BY CHURN")
print(avg_age)

# Average balance by churn
avg_balance = df.groupby('Exited')['Balance'].mean()

print("\nAVERAGE BALANCE BY CHURN")
print(avg_balance)

# Gender churn percentage
gender_churn = pd.crosstab(
    df['Gender'],
    df['Exited'],
    normalize='index'
) * 100

print("\nGENDER CHURN PERCENTAGE")
print(gender_churn)

# =====================================================
# STEP 8 - FINAL CONCLUSION
# =====================================================

print("\n===================================")
print("FINAL CONCLUSION")
print("===================================\n")

print("""
1. Older customers are more likely to churn.

2. Customers with higher account balances
   show greater churn tendency.

3. Gender has some influence on churn behavior.

4. Balance and salary have weak correlation.

5. Statistical tests validate important
   churn patterns in the dataset.

6. Banks can improve retention strategies
   by targeting high-risk customers.
""")